package dev.testsleuth.core.event;

public enum EventKind {
    BUILD_STARTED,
    BUILD_FINISHED,
    MODULE_STARTED,
    MODULE_FINISHED,
    TEST_DISCOVERED,
    TEST_STARTED,
    TEST_FINISHED,
    SETUP_STARTED,
    SETUP_FINISHED,
    TEARDOWN_STARTED,
    TEARDOWN_FINISHED,
    FRAMEWORK_INITIALIZATION_STARTED,
    FRAMEWORK_INITIALIZATION_FINISHED,
    INFRASTRUCTURE_STARTED,
    INFRASTRUCTURE_FINISHED,
    WAIT_STARTED,
    WAIT_FINISHED
}

